// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package observer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[START_SPAN-1]
	_ = x[FINISH_SPAN-2]
	_ = x[ADD_EVENT-3]
	_ = x[NEW_SCOPE-4]
	_ = x[MODIFY_ATTR-5]
	_ = x[SET_STATUS-6]
	_ = x[GAUGE_SET-7]
	_ = x[CUMULATIVE_INC-8]
	_ = x[ADDITIVE_ADD-9]
	_ = x[MEASURE_RECORD-10]
}

const _EventType_name = "INVALIDSTART_SPANFINISH_SPANADD_EVENTNEW_SCOPEMODIFY_ATTRSET_STATUSGAUGE_SETCUMULATIVE_INCADDITIVE_ADDMEASURE_RECORD"

var _EventType_index = [...]uint8{0, 7, 17, 28, 37, 46, 57, 67, 76, 90, 102, 116}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
