// Code generated by "stringer -type=Type"; DO NOT EDIT.

package attribute

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INVALID-0]
	_ = x[BOOL-1]
	_ = x[INT64-2]
	_ = x[FLOAT64-3]
	_ = x[STRING-4]
	_ = x[BYTES-5]
	_ = x[BOOLSLICE-6]
	_ = x[INT64SLICE-7]
	_ = x[FLOAT64SLICE-8]
	_ = x[STRINGSLICE-9]
}

const _Type_name = "INVALIDBOOLINT64FLOAT64STRINGBYTESBOOLSLICEINT64SLICEFLOAT64SLICESTRINGSLICE"

var _Type_index = [...]uint8{0, 7, 11, 16, 23, 29, 34, 43, 53, 65, 76}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
