// Code generated by "stringer -type=MetricType"; DO NOT EDIT.

package metric

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Gauge-1]
	_ = x[Cumulative-2]
	_ = x[Additive-3]
	_ = x[Measure-4]
}

const _MetricType_name = "InvalidGaugeCumulativeAdditiveMeasure"

var _MetricType_index = [...]uint8{0, 7, 12, 22, 30, 37}

func (i MetricType) String() string {
	if i < 0 || i >= MetricType(len(_MetricType_index)-1) {
		return "MetricType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MetricType_name[_MetricType_index[i]:_MetricType_index[i+1]]
}
