// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package aggregation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[SUM-1]
	_ = x[COUNT-2]
	_ = x[MIN-3]
	_ = x[MAX-4]
	_ = x[LAST_VALUE-5]
	_ = x[DISTRIBUTION-6]
}

const _Operator_name = "NONESUMCOUNTMINMAXLAST_VALUEDISTRIBUTION"

var _Operator_index = [...]uint8{0, 4, 7, 12, 15, 18, 28, 40}

func (i Operator) String() string {
	if i < 0 || i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
